{% set name = "iris-sample-data" %}
{% set version = "2.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 83849e6cfc2ffcadf25392f2c855227b413018bb30254b92af8a2594a611d5ba

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=45
    - setuptools-scm >=6.2
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - iris_sample_data

about:
  home: https://github.com/SciTools/iris-sample-data
  license: OGL-UK-3.0
  license_family: OTHER
  summary: Iris sample data.

extra:
  recipe-maintainers:
    - ocefpaf
    - bjlittle
    - DPeterK
    - trexfeathers
    - stephenworsley
