{% set name = "iris-sample-data" %}
{% set version = "2.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 09364a111533c628fc604d935159ad477927d5a8cef1bb6b25f0b18462bea157

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - setuptools-scm
  run:
    - python

test:
  imports:
    - iris_sample_data

about:
  home: https://github.com/SciTools/iris-sample-data
  license: Open Government
  license_family: OTHER
  summary: Iris sample data.

extra:
  recipe-maintainers:
    - ocefpaf
    - bjlittle
    - DPeterK
    - trexfeathers
