travis:
  secure:
    BINSTAR_TOKEN: TEWefhlnroM78gYkgrH2pFLPCpexxY0hvY1l9OSt/kLfiVL7EaTQrr4J8yeBn4aZAIPmWd/Os/Hcm6wLI0kJGwH6clLEus4Trh6wXN6ssTKdWI5RIHjm8X32DU3JgxGGC7SEQ54WLorfNRVRZGk8VHKTya+kbkMTNM52E+ynKcD98/kuPhSXUW8ZCgnlPgaxf0ADl0Bhj3Y2BTNbUlqogjkubV8TfB/yay181WF8PbcIycGlEOHD1EYiQkj9WOdeA/XdTH3RrBjJ2KZ7iS8aK9Uu1rhiimgLrtenwP3ouJD13yJCcjIL4dwwbKrRULoMu96SmbPXImwRH41Bd2Tu30LLEjWAnA0Q/DU9bFLtoVtJQ8K5/4eLZ85qSSyiceSG2fYKogIiSfrk/EC6lGYzdBOLNa4weCrKC+QfmH0giyzLjkca5uZWTCj3jF+cdMfy8M7q0SSJQmlNfpMzpvHsSZpcGh0dtRnNwldqLXHDqP3VKjEbTfxjYLubWf5U+m57+WI2kv2Fp1aijz494QxPNvA1ll2dYjdpRNmOEaJCJK66Q+hPYUrwo45zehw0VmyqQPhu7bbmLdq/mR1JkoT7Aj7w8ioJ7ZsYE7/N2IcuRyQzYvN/GrvoVJMwu/GtB3ZQF+TWQ86EKRfiMDdAqcEYdQ3F+Imds0eLEBd8zjgXqBU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
